//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public cours()
        {
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string image_url { get; set; }
        public string tutor { get; set; }
        public int rating { get; set; }
        public int cost { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
