//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("udemyModel", "FK__users__course_id__46E78A0C", "courses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Udemy.cours), "users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Udemy.user), true)]

#endregion

namespace Udemy
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class udemyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new udemyEntities object using the connection string found in the 'udemyEntities' section of the application configuration file.
        /// </summary>
        public udemyEntities() : base("name=udemyEntities", "udemyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new udemyEntities object.
        /// </summary>
        public udemyEntities(string connectionString) : base(connectionString, "udemyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new udemyEntities object.
        /// </summary>
        public udemyEntities(EntityConnection connection) : base(connection, "udemyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cours> courses
        {
            get
            {
                if ((_courses == null))
                {
                    _courses = base.CreateObjectSet<cours>("courses");
                }
                return _courses;
            }
        }
        private ObjectSet<cours> _courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocourses(cours cours)
        {
            base.AddObject("courses", cours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="udemyModel", Name="cours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cours object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="image_url">Initial value of the image_url property.</param>
        /// <param name="tutor">Initial value of the tutor property.</param>
        /// <param name="rating">Initial value of the rating property.</param>
        /// <param name="cost">Initial value of the cost property.</param>
        public static cours Createcours(global::System.Int32 id, global::System.String title, global::System.String image_url, global::System.String tutor, global::System.Int32 rating, global::System.Int32 cost)
        {
            cours cours = new cours();
            cours.id = id;
            cours.title = title;
            cours.image_url = image_url;
            cours.tutor = tutor;
            cours.rating = rating;
            cours.cost = cost;
            return cours;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String image_url
        {
            get
            {
                return _image_url;
            }
            set
            {
                Onimage_urlChanging(value);
                ReportPropertyChanging("image_url");
                _image_url = StructuralObject.SetValidValue(value, false, "image_url");
                ReportPropertyChanged("image_url");
                Onimage_urlChanged();
            }
        }
        private global::System.String _image_url;
        partial void Onimage_urlChanging(global::System.String value);
        partial void Onimage_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tutor
        {
            get
            {
                return _tutor;
            }
            set
            {
                OntutorChanging(value);
                ReportPropertyChanging("tutor");
                _tutor = StructuralObject.SetValidValue(value, false, "tutor");
                ReportPropertyChanged("tutor");
                OntutorChanged();
            }
        }
        private global::System.String _tutor;
        partial void OntutorChanging(global::System.String value);
        partial void OntutorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rating
        {
            get
            {
                return _rating;
            }
            set
            {
                OnratingChanging(value);
                ReportPropertyChanging("rating");
                _rating = StructuralObject.SetValidValue(value, "rating");
                ReportPropertyChanged("rating");
                OnratingChanged();
            }
        }
        private global::System.Int32 _rating;
        partial void OnratingChanging(global::System.Int32 value);
        partial void OnratingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cost
        {
            get
            {
                return _cost;
            }
            set
            {
                OncostChanging(value);
                ReportPropertyChanging("cost");
                _cost = StructuralObject.SetValidValue(value, "cost");
                ReportPropertyChanged("cost");
                OncostChanged();
            }
        }
        private global::System.Int32 _cost;
        partial void OncostChanging(global::System.Int32 value);
        partial void OncostChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("udemyModel", "FK__users__course_id__46E78A0C", "users")]
        public EntityCollection<user> users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user>("udemyModel.FK__users__course_id__46E78A0C", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user>("udemyModel.FK__users__course_id__46E78A0C", "users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="udemyModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="course_id">Initial value of the course_id property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="passcode">Initial value of the passcode property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String first_name, global::System.String last_name, global::System.Int32 course_id, global::System.String email, global::System.String username, global::System.String passcode)
        {
            user user = new user();
            user.id = id;
            user.first_name = first_name;
            user.last_name = last_name;
            user.course_id = course_id;
            user.email = email;
            user.username = username;
            user.passcode = passcode;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false, "first_name");
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false, "last_name");
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 course_id
        {
            get
            {
                return _course_id;
            }
            set
            {
                Oncourse_idChanging(value);
                ReportPropertyChanging("course_id");
                _course_id = StructuralObject.SetValidValue(value, "course_id");
                ReportPropertyChanged("course_id");
                Oncourse_idChanged();
            }
        }
        private global::System.Int32 _course_id;
        partial void Oncourse_idChanging(global::System.Int32 value);
        partial void Oncourse_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String passcode
        {
            get
            {
                return _passcode;
            }
            set
            {
                OnpasscodeChanging(value);
                ReportPropertyChanging("passcode");
                _passcode = StructuralObject.SetValidValue(value, false, "passcode");
                ReportPropertyChanged("passcode");
                OnpasscodeChanged();
            }
        }
        private global::System.String _passcode;
        partial void OnpasscodeChanging(global::System.String value);
        partial void OnpasscodeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("udemyModel", "FK__users__course_id__46E78A0C", "courses")]
        public cours cours
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cours>("udemyModel.FK__users__course_id__46E78A0C", "courses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cours>("udemyModel.FK__users__course_id__46E78A0C", "courses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cours> coursReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cours>("udemyModel.FK__users__course_id__46E78A0C", "courses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cours>("udemyModel.FK__users__course_id__46E78A0C", "courses", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
